# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*\.svg
          )$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
-   repo: https://github.com/python-poetry/poetry
    rev: "2.1.3"
    hooks:
    -   id: poetry-check
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
    -   id: pyproject-fmt
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        exclude: |
          (?x)^(
              .*\.lock |
              .*\.json |
              .*\.ipynb |
              .*\.cppipe
          )$
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
-   repo: https://github.com/citation-file-format/cffconvert
    rev: b6045d78aac9e02b039703b030588d54d53262ac
    hooks:
    -   id: validate-cff
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
    -   id: yamllint
        exclude: pre-commit-config.yaml
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    -   id: actionlint
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.11"
    hooks:
    -   id: ruff-format
    -   id: ruff-check
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'
    hooks:
    -   id: vulture
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.0
    hooks:
    -   id: pre-commit-update
        args: ["--keep", "mdformat", "--keep", "pre-commit-update", "--keep", "cffconvert"]
-   repo: local
    hooks:
    -   id: code-cov-gen
        name: Generate code coverage
        language: system
        entry: poetry run coverage run -m pytest
        pass_filenames: false
        always_run: true
-   repo: https://github.com/Weird-Sheep-Labs/coverage-pre-commit
    rev: 0.1.1
    hooks:
    -   id: coverage-xml
    -   id: coverage-badge
        args: ["-o", "media/coverage-badge.svg"]
