# GitHub Issue template for bug reports
name: Open a GitHub issue
description: >
  Please use this form to send along new ideas for content or
  changes that might be helpful!

body:
  - type: checkboxes
    attributes:
      label: Is this a duplicate of an existing idea for this project?
      description: >
        Please make sure to search in the
        [issues](https://github.com/WayScience/coSMicQC/issues) first
        to see whether the same issue was reported already.
        If you find an existing issue, please don't hesitate to comment
        on it or add a reaction to existing content!
      options:
        - label: >
            I found no existing
            [issues](https://github.com/WayScience/coSMicQC/issues)
            covering this topic.
          required: true

  - type: textarea
    id: description
    attributes:
      label: What is your idea?
      description: >
        Please provide a specific description of what you'd like to see
        including the context and what the result might look like.
      placeholder: >
        For example: "When x happens I see y.
        The following might be a good way to address this ..."
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Would you like to work on a solution for this?
      description: >
        This is a community-driven project and we
        love new contributors (including through opening or adding to issues)!
        This is an optional check to help us understand your interest to be
        involved (especially if you already have a good understanding
        of how to implement it).
        We are happy to guide you in the contribution process and please
        don't hesitate to reach out for help along the way.
      options:
        - label: Yes I am willing to submit a PR for this!
