---
# used for publishing documentation on push to main or published release
name: publish docs

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check git tags
        run: |
          git for-each-ref --format "%(refname)" | sed 's/^refs\///g'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup for poetry
        run: |
          python -m pip install poetry poetry-dynamic-versioning
      - name: poetry deps
        run: poetry install
      - name: Build documentation
        run: |
          mkdir pages
          touch pages/.nojekyll
          cd docs
          poetry run sphinx-multiversion src build
          cp -r build/* ../pages/
      - name: Add index redirector to latest docs
        run: |
          cp docs/redirector.html pages/index.html
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: pages
